services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      U2NET_HOME: /rembg_models
    volumes:
      - .cache/rembg_models:/rembg_models
    ports:
      - 8000:8000
